name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo true/false
        run: |
          echo false: ${{ startsWith(github.ref, 'refs/heads') }}
          echo true: ${{ startsWith(github.ref, 'refs/tags') }}
