name: CI

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    name: dummy_check
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: echo true/false
        run: |
          echo false: ${{ startsWith(github.ref, 'refs/heads') }}
          echo true: ${{ startsWith(github.ref, 'refs/tags') }}
